name: Build Test (No Release)

on:
  workflow_dispatch: # Manual trigger only
  pull_request: # Optional: test on PRs
    branches:
      - main

jobs:
  test-build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install Rust target (macOS ARM only)
        if: matrix.platform.target == 'aarch64-apple-darwin'
        run: rustup target add aarch64-apple-darwin

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app (TEST - NO RELEASE)
        uses: tauri-apps/tauri-action@v0.5
        with:
          # Important: No tagName means no release will be created
          args: --target ${{ matrix.platform.target }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vtproxy-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: |
            src-tauri/target/${{ matrix.platform.target }}/release/bundle/**/*
          retention-days: 7
